AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Fargate Auto Scaling Web Server with RDS"

Parameters:
  StackName:
    Type: String
  BaseDomainName:
    Type: String
    Description: "The base domain name for the application. Subdomain of
      StackName will be used"
    Default: appalachiancoding.org
  HostedZoneId:
    Type: String
    Default: Z09827882WIF0Q8AI3TUF
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.101.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.102.0/24

Resources:
  # Networking
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${StackName}-vpc-id"
      CidrBlock: !Ref PublicSubnet1Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
  PublicSubnet1RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue
        Fn::Sub: ${StackName}-public-route-table
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${StackName}-vpc-id"
      CidrBlock: !Ref PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs ""]
  PublicSubnet2RTA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue
        Fn::Sub: ${StackName}-public-route-table
      SubnetId: !Ref PublicSubnet2

  # ALB
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTPS access"
      VpcId: !ImportValue
        Fn::Sub: "${StackName}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${StackName}-backend"
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "${StackName}.${BaseDomainName}"
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !Sub "${StackName}.${BaseDomainName}"
        - !Sub "api.${StackName}.${BaseDomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "${StackName}.${BaseDomainName}"
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "api.${StackName}.${BaseDomainName}"
          HostedZoneId: !Ref HostedZoneId


  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTarget
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref Certificate

  FrontendTarget:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Port: 80
      TargetType: ip
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: "${StackName}-vpc-id"
  FrontendRoute:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "${StackName}.${BaseDomainName}"
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt LoadBalancer.DNSName

  BackendTarget:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/health"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Port: 80
      TargetType: ip
      Protocol: HTTP
      VpcId: !ImportValue
        Fn::Sub: "${StackName}-vpc-id"
  BackendRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTarget
      Conditions:
        - Field: host-header
          Values:
            - !Sub "api.${StackName}.${BaseDomainName}"
      ListenerArn: !Ref Listener
      Priority: 1
  BackendRoute:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${BaseDomainName}."
      Name: !Sub "api.${StackName}.${BaseDomainName}"
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt LoadBalancer.DNSName

Outputs:
  BackendTargetGroup:
    Value: !Ref BackendTarget
    Export:
      Name: !Sub "${StackName}-backend-alb-tg-arn"
  FrontendTargetGroup:
    Value: !Ref FrontendTarget
    Export:
      Name: !Sub "${StackName}-frontend-alb-tg-arn"
  Endpoint:
    Value: !Sub "https://${StackName}.${BaseDomainName}"
    Export:
      Name: !Sub "${StackName}-alb-dns-name"
