name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::864899846218:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Run Deploy Script
        run: |
          chmod +x ./deploy/deploy.sh
          ./deploy/deploy.sh dnd-unsecured

      - name: Check Deployment Health
        run: |
          sleep 10
          curl --fail https://api.dnd-unsecured.appalachiancoding.org/health
